version: "3.7"

services:
  web:
    build:
      context: ./php-apache
    ports:
      - 80:80
      - 8000:8000
      - 5173:5173
    volumes:
      - ./htdocs:/var/www/html
  db:
    build:
      context: ./mysql
    volumes:
      - ./mysqlvol:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  phpmyadmin:
    build:
      context: ./phpmyadmin
    depends_on:
      - db
    links:
      - db
    ports:
      - "8088:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions